### ISSUE TITLE
As an author I want to generate an email to my librarian

### ISSUE THREAD

**Issue by joemull** [openlibhums/consortial_billing#74]
Requested by @rhb123 -- thanks Rose!

## User story

As an author, editor, or reader with a good experience of the OLH, I'd like a tool that lets me check if my university is a current supporter and generates an email for me to send to my librarian to ask them to support the OLH.

## Proposed solution

A three-step form with no authentication and no saves to the database, using Hourglass styling:
1. I can search for my institution, and JW tells me if we're already a supporter or not by returning any matching current supporter records. (We could do this without ROR in the short-term, though it would not be as robust.)
2. If I don't see a current supporter that matches my university, I can click to the next page where I can search for and select a published article that I had authored, edited, or read. I'd have to specify what role I had when selecting the article.
3. When I select an article, JW generates some text for me that I can copy and paste into an email to the librarian of my choice. The text generated would change depending on my role.

Example text from Rose:

'Dear Librarian,  I am writing to ask if the library would be able to join the Open Library of Humanities please? I recently published my paper 'title of paper' in 'title of OLH journal' with the Open Library of Humanities and I was very impressed with their publication process and excellent cause as a diamond open access publisher (see https://openlibhums.org/plugins/supporters/signup/ for details). Many thanks.'

## Also considered

Eventually the tool might consider these things with additional features

- The institution is currently a supporter but at the standard tier, and the user wants to recommend a higher tier

**Comment by rhb123** [comment]
Thanks for writing this up Joe - some more details to help here:

- Ease and speed of use are very important to make it as smooth and quick as possible for folks to use the tool. We are on borrowed time and asking folks to do us a favour with this, so we need to make it super slick and as intuitive and simple as we can.

- As such, when functionality permits it would be great to do this in a single webpage if possible, to avoid the visual jump of having to go to another webpage. Clicking through to another page immediately would prompt the user to wonder how many pages this is / how much longer it will take and possibly give up, so would be good to avoid this if at all possible. 

- If it's possible to embed the generated text into an email with one click that would be great - ie, so click 'Email now' and it opens a new email in outlook with relevant subject line and email body auto-populated, so that the user just needs to paste in their librarian's email address and click 'send'. 

- We need to add a very brief box with guidance on how to use, so would suggest breaking it down into clear steps so that folks know how to use it. Ie 1) Fill in your details; 3) Click to generate text; 4) Click to populate email; 4) Send to your library. The latter would need to have some form of advice / popup help for 'Who should I email?' with a brief note to look on your institution's library webpage to find your library's email address. Note I've deliberately left the first part, which would be to check whether your library is a supporter, out of the above list of steps as presumably they'd only be taken to the tool if their library wasn't listed in the initial search, ie, you're taken to the start of the tool if you click 'My institution isn't listed'.

- If it isn't possible to auto-populate titles of papers and journals it would be ok for these to be added manually to allow folks to type these in, in case this gets too tricky.

- I would suggest adding an 'other' type category would also be very sensible, so that for step one you can choose if you're an author / editor / reader / other, with the latter generating short text that says we are doing awesome work in open access and their library should support us, so that it can be used in all situations (ie, by JW clients etc, anyone else we help out).

- After filling this in, we could potentially extend with the ability for the user to send an email to recommend the tool to someone else, and automate text with share buttons for social media. Ie, 'I've just asked my library to join the OLH to help keep knowledge free, and I think you should too.'

- As the look and feel is important I would suggest it may be recruiting Carly to help with an eye-catching design once it's been coded.

- If we were able to capture the number of uses or other data without too much faff here that may be useful to help us hone for future.


Once we get this fully working, we'd then need to get this out as widely as we can. I would suggest:

*Adding hyperlinked text to team email signatures, ie: 'Like what we do? {Ask your library to join us!}'

*Team proactively encouraging satisfied users to use the tool, and (crucially) let us know how they get on if they agree to use it / follow up to ask how they found it. Opportunities to use this include:

-  satisfied OLHJ authors, editors and readers;
-  editorial teams of OLH journals;
-  satisfied JW clients / users;
- add to publisher footer across all OLH journals, ie, 'Published by Open Library of Humanities | Privacy Policy | Ask your Library to join us';
- add nicely designed 'Ask your library to join us.' clickable button badge to right hand side of top menu across OLH main website and cross-link with relevant pages;
- social media campaigns with periodic cross-platform pushes from PCV;
- add to OLHJ automated email template with congratulations on publication.

**Comment by joemull** [comment]
More things for discussion:

* ![image](https://github.com/user-attachments/assets/ebe728a9-d915-4b54-a0b0-343826366bca)

* https://hds.hel.fi/components/step-by-step/

* https://designnotes.blog.gov.uk/2015/07/03/one-thing-per-page/

**Comment by joemull** [comment]
Notes from discussion with Rose:

* Author - search article
* Editor - search journal
* Reader - search article
* Other - skip search and have a template that works without any referenced work

**Comment by rhb123** [comment]
Updated 11.11.24 to add a request to add a thank you email for existing supporters as at https://github.com/openlibhums/consortial_billing/issues/86 @joemull - many thanks!
